export const permisosCaja = [
  { id: 1, nombre: 'Compra-venta/Compra' },
  { id: 2, nombre: 'Compra-venta/Venta' },
  { id: 3, nombre: 'Compra-venta/Recargas' },
  { id: 4, nombre: 'Recargas/Recargar Saldo' },
  { id: 4, nombre: 'Recargas/Verificar Saldo' },
  { id: 5, nombre: 'Inventario/Inventario' },
  { id: 6, nombre: 'Catálogo/Cambiar Contraseña' },
  { id: 7, nombre: 'Registros/Registrar Proveedores' },
  { id: 8, nombre: 'Registros/Registrar Clientes' },
  { id: 9, nombre: 'Registros/Registrar Productos' },
  { id: 10, nombre: 'Registros/Registrar departamento' },
  { id: 11, nombre: 'Registros/Registrar marca' },
  { id: 12, nombre: 'Registros/Registrar modelo' },
  { id: 13, nombre: 'Caja/Fondo de Caja' },
  { id: 14, nombre: 'Caja/Gastos' },
  { id: 15, nombre: 'Caja/Retiros' },
  { id: 16, nombre: 'Otros/Verificar Precio' },
  { id: 17,  nombre: 'Agenda/Agenda'},
  { id: 18,  nombre: 'Dashboard'},
  { id: 19,  nombre: 'Soporte'},
  { id: 42, nombre: 'Caja/CXC clientes' },
];

export const permisosGerencia = [
  { id: 20, nombre: 'Catálogo/Configuracion' },
  { id: 21, nombre: 'Catálogo/Empresa' },
  { id: 22,  nombre:'Reportes/Reportes'},
  { id: 23, nombre: 'Compra-Venta/Devolución Producto' },
  { id: 24, nombre: 'Inventario/Kardex' },
  { id: 25, nombre: 'Inventario/Cambio de precios' },
  { id: 26,  nombre: 'Caja/Corte de dia'},
  { id: 27,  nombre: 'Caja/historial'},
  { id: 28,  nombre: 'Caja/Inversiones'},
  { id: 29,  nombre: 'Gerente/GerenteCrov'},
  { id: 37, nombre: 'Compra-Venta/Devolución Compra' },
  { id: 38, nombre: 'Dashboard/Tarjetas informativas' },
  { id: 40, nombre: 'Inventario/Plantilla Excel' },
  { id: 41, nombre: 'Inventario/Importar datos Excel' },
  //{ id: 23, nombre: 'Compra-Venta/Ordenes de compra' },
  //{ id: 25, nombre: 'Compra-Venta/Compras Sugeridas' },
  //{ id: 26, nombre: 'Facturación/Facturación' },
  //{ id: 27, nombre: 'Facturación/Facturación Público General' },
  //{ id: 28, nombre: 'Facturación/Historial Facturas' },
  //{ id: 29, nombre: 'Facturación/Complemento Pago' },
  //{ id: 30, nombre: 'Recargas y Servicios/Verificar saldo' },
  //{ id: 31, nombre: 'Recargas y Servicios/Recargar saldo' },
  //{ id: 32, nombre: 'Recargas y Servicios/Historial recargas' },
  //{ id: 33, nombre: 'Recargas y Servicios/Pagar servicio' },
  //{ id: 34, nombre: 'Recargas y Servicios/Historial pago de servicios' },
  //{ id: 35, nombre: 'Inventario/Inventario' },
  //{ id: 35, nombre: 'Inventario/Historial De Inventario' },
  //{ id: 36, nombre: 'Inventario/Cotejo' },
];

export const permisosAdmin =  [
  { id: 30, nombre: 'Registros/Registrar_usuarios'},
  { id: 31, nombre: 'Usuarios/agregar_usuario'},
  { id: 32, nombre: 'Usuario/editar_permisos' },
  { id: 33, nombre: 'Usuarios/eliminar_usuario'},
  { id: 34, nombre: 'Usuario/editar_permisos' },
  { id: 35, nombre: 'Membresia' },
  { id: 36, nombre: 'Crear cuenta TAECEL' },
  { id: 39, nombre: 'Solicitud de Spin Negocios'}
];
export const permisosPorPerfil: Record<string, { id: number; nombre: string }[]> = {
  Administrador: [...permisosCaja, ...permisosGerencia, ...permisosAdmin],
  Gerencia: [...permisosCaja, ...permisosGerencia],
  Caja: permisosCaja,
};