CREATE TABLE `Plantilla` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(191) NOT NULL,
  `mensaje` TEXT NOT NULL,
  `activo` INTEGER NOT NULL DEFAULT 1,
  `creadoEn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actualizadoEn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;